DROP SCHEMA IF EXISTS TEST;

CREATE SCHEMA TEST;

DROP TABLE IF EXISTS POST;

DROP TABLE IF EXISTS ANIMAL;

CREATE TABLE PUBLIC.ANIMAL(
    ANIMALID SERIAL PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL,
    FURCOLOR VARCHAR(30) NOT NULL,
    EYECOLOR VARCHAR(30) NOT NULL,
    ACCESSORY TEXT NOT NULL,
    BREED VARCHAR(25) NOT NULL,
    SPECIES VARCHAR(25) NOT NULL,
    IMAGEPATH VARCHAR(100) NOT NULL
);

CREATE TABLE PUBLIC.POST(
    POSTID SERIAL PRIMARY KEY,
    ANIMALID INTEGER REFERENCES ANIMAL(ANIMALID),
    USERID INTEGER NOT NULL,
    TITLE VARCHAR(40) NOT NULL,
    CONTENT TEXT,
    CREATEDAT DATE DEFAULT NOW() NOT NULL,
    COMPLETEDAT DATE,
    STATUS VARCHAR(30) NOT NULL
);

INSERT INTO ANIMAL (
    NAME,
    FURCOLOR,
    EYECOLOR,
    ACCESSORY,
    BREED,
    SPECIES,
    IMAGEPATH
) VALUES (
    'Benekli',
    'beyaz',
    'kahverengi',
    'stuff',
    'something',
    'something',
    'something'
);

INSERT INTO POST (animalid, userid, title, content, completedat, status) VALUES (1, 100, 'kayip', NULL, NULL, 'active');